CREATE SCHEMA exame_hunter;

use exame_hunter;

CREATE TABLE administrador (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    email VARCHAR(45) NOT NULL,
    senha VARCHAR(45) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE candidato (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    peso DECIMAL NOT NULL,
    altura DECIMAL NOT NULL,
    dataNascimento DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 

CREATE TABLE examinador (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    peso DECIMAL NOT NULL,
    altura DECIMAL NOT NULL,
    dataNascimento DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 

CREATE TABLE tipoNen (
    id INT AUTO_INCREMENT PRIMARY KEY,
	descricao VARCHAR(45) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 

CREATE TABLE examinador_tipoNen (
    examinador_id INT,
    tipoNen_id INT,
    PRIMARY KEY(examinador_id, tipoNen_id),
    FOREIGN KEY (examinador_id) REFERENCES examinador(id) ON DELETE CASCADE,
    FOREIGN KEY (tipoNen_id) REFERENCES tipoNen(id) ON DELETE CASCADE
);